[package]
name = "inspect_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.54"
primes_table_gen = {path="../../crates/primes_table_gen"}